name: "[CI] Lint"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.2.2

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop -P -f github
